---
kind: pipeline
name: default

type: docker
steps:
  - name: bake
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: rubasace/drone-helm-k8s
      tags:
        - 1.0.0.${CI_BUILD_NUMBER}
        - latest
    when:
      branch:
        - master
---
kind: signature
hmac: 2cbf6af5539faaf3b307964a353067d6969d4c4e22bf5b32266255f55e849828

...
