---
kind: pipeline
name: default
type: docker

steps:
  - name: bake
    secrets: [ docker_username, docker_password ]
    image: plugins/docker
    repo: rubasace/drone-helm-k8s
    tags:
      - 1.0.0.${CI_BUILD_NUMBER}
      - latest
    when:
      branch:
        - master
---
kind: signature
hmac: c59895e6b922305c82fe46ca68d733c4a9c91f0dfd51b42630ccd0a7af8aa963

...
