---
kind: pipeline
name: default

type: docker
steps:
  - name: bake
    image: plugins/docker
    settings:
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
      repo: rubasace/drone-helm-k8s
      tags:
        - 1.0.0.${CI_BUILD_NUMBER}
        - latest
    when:
      branch:
        - master
---
kind: signature
hmac: 08cac761ffcc66648f9cb143e018f92bc7258d8fc07cb507eecd34ef5a08d5f0

...
